---
version : '3'
services:
  webapp:
    image: tomcat:8-jre8-alpine
    environment:
      JDBC_URL: jdbc:mysql://database:3306/project
      JDBC_USER: root
      JDBC_PASS: password
    ports:
     - "8080:8080"
    volumes:
     - ./tomcat/webapps:/usr/local/tomcat/webapps
    depends_on:
     - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project
    ports:
     - "3306:3306"
    expose:
     - 3306
    volumes:
     - ./db:/docker-entrypoint-initdb.d
